export const gallerySpanOptions = [
  "col-span-1 row-span-1",
  "col-span-2 row-span-1",
  "col-span-1 row-span-2",
  "col-span-2 row-span-2",
];

export const roomCategoryOptions = ["Suite", "Villa", "Penthouse", "Deluxe", "Loft"];

export const adminSchema = [
  {
    key: "hotelInfo",
    label: "Hotel Info",
    table: "hotel_info",
    singleton: true,
    description: "Global details used across the whole site — hero, CTA and about sections included.",
    fields: [
      { name: "name", label: "Hotel Name", type: "text" },
      { name: "tagline", label: "Tagline", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "email", label: "Email", type: "text" },
      { name: "phone", label: "Phone", type: "text" },
      { name: "location", label: "Location", type: "text" },
      { name: "founded", label: "Founded (year)", type: "text" },
      { name: "heroBadge", label: "Hero Badge", type: "text" },
      { name: "heroTitle", label: "Hero Title", type: "text" },
      { name: "heroTitleAccent", label: "Hero Title Accent Word", type: "text" },
      { name: "heroSubtitle", label: "Hero Subtitle", type: "textarea" },
      { name: "ctaBadge", label: "CTA Badge", type: "text" },
      { name: "ctaTitle", label: "CTA Title", type: "text" },
      { name: "ctaText", label: "CTA Text", type: "textarea" },
      {
        name: "aboutStory",
        label: "About Story",
        type: "textarea",
        hint: "Separate paragraphs with a blank line.",
      },
      { name: "aboutImage", label: "About Image URL", type: "image" },
    ],
  },
  {
    key: "rooms",
    label: "Rooms",
    table: "rooms",
    displayField: "name",
    imageField: "image",
    subtitleField: (room) => `${room.category} · $${room.price}/night`,
    fields: [
      { name: "sortOrder", label: "Sort Order", type: "number" },
      { name: "name", label: "Name", type: "text" },
      { name: "slug", label: "Slug", type: "text", hint: "Used in the URL, e.g. horizon-suite" },
      { name: "category", label: "Category", type: "select", options: roomCategoryOptions },
      { name: "price", label: "Price per Night ($)", type: "number" },
      { name: "size", label: "Size (m²)", type: "number" },
      { name: "maxGuests", label: "Max Guests", type: "number" },
      { name: "bedType", label: "Bed Type", type: "text" },
      { name: "floor", label: "Floor", type: "text" },
      { name: "image", label: "Cover Image URL", type: "image" },
      { name: "gallery", label: "Gallery Image URLs", type: "images" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "amenities", label: "Amenities", type: "tags", hint: "One amenity per line." },
    ],
    defaults: {
      sortOrder: 99,
      category: "Suite",
      maxGuests: 2,
      bedType: "King",
      floor: "",
      gallery: [],
      amenities: [],
    },
  },
  {
    key: "experiences",
    label: "Experiences",
    table: "experiences",
    displayField: "title",
    imageField: "image",
    subtitleField: (exp) => exp.description,
    fields: [
      { name: "sortOrder", label: "Sort Order", type: "number" },
      { name: "title", label: "Title", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "image", label: "Image URL", type: "image" },
    ],
    defaults: { sortOrder: 99 },
  },
  {
    key: "stats",
    label: "Stats",
    table: "stats",
    displayField: "value",
    subtitleField: (stat) => stat.label,
    fields: [
      { name: "sortOrder", label: "Sort Order", type: "number" },
      { name: "value", label: "Value", type: "text" },
      { name: "label", label: "Label", type: "text" },
    ],
    defaults: { sortOrder: 99 },
  },
  {
    key: "testimonials",
    label: "Testimonials",
    table: "testimonials",
    displayField: "author",
    subtitleField: (t) => `${t.origin} · ${"★".repeat(t.rating || 0)}`,
    fields: [
      { name: "sortOrder", label: "Sort Order", type: "number" },
      { name: "text", label: "Quote", type: "textarea" },
      { name: "author", label: "Author", type: "text" },
      { name: "origin", label: "Origin", type: "text" },
      { name: "rating", label: "Rating (1–5)", type: "number" },
    ],
    defaults: { sortOrder: 99, rating: 5 },
  },
  {
    key: "values",
    label: "Core Values",
    table: "core_values",
    displayField: "title",
    subtitleField: (val) => val.description,
    fields: [
      { name: "sortOrder", label: "Sort Order", type: "number" },
      { name: "icon", label: "Icon (character/emoji)", type: "text" },
      { name: "title", label: "Title", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
    ],
    defaults: { sortOrder: 99, icon: "✦" },
  },
  {
    key: "galleryImages",
    label: "Gallery",
    table: "gallery_images",
    displayField: "alt",
    imageField: "src",
    subtitleField: (img) => img.span,
    fields: [
      { name: "sortOrder", label: "Sort Order", type: "number" },
      { name: "src", label: "Image URL", type: "image" },
      { name: "alt", label: "Alt Text", type: "text" },
      {
        name: "span",
        label: "Grid Span",
        type: "select",
        options: gallerySpanOptions,
      },
    ],
    defaults: { sortOrder: 99, span: "col-span-1 row-span-1" },
  },
];
